// <auto-generated />
namespace InternetShop.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AppUser11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppUser11));
        
        string IMigrationMetadata.Id
        {
            get { return "201803291754350_AppUser1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
